import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function SolutionLayout({
  children,
}: {
  children: React.ReactNode;
}) {    
  return (
      <>
      <header
          style={{
            backgroundColor: "brown",
            padding: "1rem",
          }}
        >
          <p>Solution Header</p>
        </header>
        {children}
        <footer
          style={{
            backgroundColor: "ghostwhite",
            padding: "1rem",
          }}
        >
          <p>Solution Footer</p>
        </footer>
      </>
  );
}
